// Generated by `opennextjs-cloudflare build`; present only after that runs, which
// is why the deploy script always builds before bundling.
import openNextHandler from './.open-next/worker.js';
import { fxDbFromEnv, hasSucceededToday, refreshFxRates } from './src/lib/services/fx';

/**
 * The Worker entry point.
 *
 * OpenNext generates a worker that exports only `fetch`, and a Cloudflare Cron
 * Trigger needs a `scheduled` export. Rather than patch generated output, this
 * wraps it: `fetch` is delegated untouched, and `scheduled` is ours.
 *
 * `scheduled` runs outside any request, so OpenNext has not populated
 * `process.env` — the database client has to be built from the `env` argument
 * explicitly rather than importing the request-path one.
 */
interface Env {
  DATABASE_URL?: string;
}

export default {
  fetch: openNextHandler.fetch,

  async scheduled(
    _controller: { cron: string },
    env: Env,
    ctx: { waitUntil: (p: Promise<unknown>) => void },
  ) {
    if (!env.DATABASE_URL) {
      console.error('Cron: DATABASE_URL is not set; skipping FX refresh.');
      return;
    }

    ctx.waitUntil(
      (async () => {
        const db = fxDbFromEnv(env.DATABASE_URL!);

        // The trigger fires every 2h, but only the first success each day does
        // any work. That is what gives "once a day, with automatic retries until
        // it works" without a second scheduler — a daily-only trigger would leave
        // rates a full day stale after one bad morning.
        if (await hasSucceededToday(db)) return;

        const result = await refreshFxRates(db);
        console.log(
          `Cron FX refresh: ${result.status}` +
            (result.source ? ` via ${result.source}` : '') +
            (result.error ? ` — ${result.error}` : ''),
        );
      })(),
    );
  },
};
