// Mock data for the admin Suppliers screens. Served by MSW (see
// src/mocks/handlers.ts) only when VITE_API_MOCKING=enabled; with the flag off
// the worker never starts and requests fall through to the real backend.
// Shapes mirror AdminSupplier / AdminTranslation from ./queries.

import type { AdminSupplier } from './queries';

export const SUPPLIERS: AdminSupplier[] = [
  {
    id: 'sup-denizli',
    countryCode: 'TR',
    logoUrl: 'https://images.tavkil.com/suppliers/denizli-tekstil.png',
    website: 'https://denizlitekstil.example.com',
    contactEmailInternal: 'sales@denizlitekstil.example.com',
    contactPhoneInternal: '+90 258 000 0000',
    isVerified: true,
    internalNotes: 'Reliable lead times. Primary towel supplier.',
    address: 'Saraylar Mah. 2. Ticari Yolu No: 14, Merkezefendi, Denizli, Türkiye',
    mapUrl: 'https://maps.app.goo.gl/example-denizli',
    status: 'published',
    productCount: 12,
    createdAt: '2026-01-10T09:00:00.000Z',
    updatedAt: '2026-05-18T12:00:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Denizli Tekstil',
        slug: 'denizli-tekstil',
        description: 'Family-run cotton towel and bathrobe manufacturer in Denizli.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Denizli Tekstil',
        slug: 'denizli-tekstil-tr',
        description: 'Denizli merkezli aile şirketi pamuklu havlu ve bornoz üreticisi.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'دنيزلي تكستيل',
        slug: 'denizli-tekstil-ar',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'sup-levantine',
    countryCode: 'TR',
    logoUrl: null,
    website: 'https://levantinelighting.example.com',
    contactEmailInternal: 'orders@levantinelighting.example.com',
    contactPhoneInternal: '+90 212 000 0000',
    isVerified: true,
    internalNotes: 'Good for decorative fixtures; LED panel lead time ~3 weeks.',
    address: 'Maslak Mah. Büyükdere Cd. No: 245, Sarıyer, İstanbul, Türkiye',
    mapUrl: null,
    status: 'published',
    productCount: 4,
    createdAt: '2026-01-14T09:00:00.000Z',
    updatedAt: '2026-05-19T09:30:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Levantine Lighting',
        slug: 'levantine-lighting',
        description: 'Commercial and decorative lighting manufacturer based in Istanbul.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Levantine Aydınlatma',
        slug: 'levantine-aydinlatma',
        description: 'İstanbul merkezli ticari ve dekoratif aydınlatma üreticisi.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'ليفانتين للإضاءة',
        slug: 'levantine-lighting-ar',
        description: 'شركة تصنيع إضاءة تجارية وزخرفية مقرها إسطنبول.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: true,
      },
    ],
  },
  {
    id: 'sup-aydin',
    countryCode: 'TR',
    logoUrl: null,
    website: null,
    contactEmailInternal: 'info@aydinindustrial.example.com',
    contactPhoneInternal: null,
    isVerified: false,
    internalNotes: 'New supplier — pending verification of certifications.',
    address: null,
    mapUrl: null,
    status: 'draft',
    productCount: 0,
    createdAt: '2026-02-05T09:00:00.000Z',
    updatedAt: '2026-05-26T16:20:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Aydın Industrial',
        slug: 'aydin-industrial',
        description: 'Hydraulic pumps and industrial machinery parts.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Aydın Endüstri',
        slug: 'aydin-endustri',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: '',
        slug: '',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
    ],
  },
];

/** Find a supplier by id (case-sensitive — ids are stable slugs). */
export function findSupplier(id: string | undefined): AdminSupplier | undefined {
  if (!id) return undefined;
  return SUPPLIERS.find((s) => s.id === id);
}
