// Mock data for the admin Categories screens. Served by MSW (see
// src/mocks/handlers.ts) only when VITE_API_MOCKING=enabled; with the flag off
// the worker never starts and requests fall through to the real backend.
// Shapes mirror AdminCategory / AdminTranslation from ./queries.

import type { AdminCategory } from './queries';

// Seeds omit sortStrategy; the CATEGORIES export defaults it to 'manual'.
type CategorySeed = Omit<AdminCategory, 'sortStrategy'>;

const BASE_CATEGORIES: CategorySeed[] = [
  {
    id: 'cat-textiles',
    parentId: null,
    imageUrl: 'https://images.tavkil.com/categories/textiles.jpg',
    displayOrder: 1,
    status: 'published',
    createdAt: '2026-01-12T09:00:00.000Z',
    updatedAt: '2026-05-20T11:30:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Textiles & Towels',
        slug: 'textiles-towels',
        description: 'Cotton towels, bathrobes, and home textiles from Denizli mills.',
        seoTitle: 'Wholesale Textiles & Towels',
        seoDescription: 'Source bulk cotton towels and home textiles direct from Turkish mills.',
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Tekstil & Havlu',
        slug: 'tekstil-havlu',
        description: 'Denizli üretimi pamuklu havlu, bornoz ve ev tekstili.',
        seoTitle: 'Toptan Tekstil & Havlu',
        seoDescription: 'Türk üreticilerden toptan pamuklu havlu ve ev tekstili.',
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'المنسوجات والمناشف',
        slug: 'almansujat-walmanashif',
        description: 'مناشف قطنية وأرواب ومنسوجات منزلية من مصانع دنيزلي.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: true,
      },
    ],
  },
  {
    id: 'cat-lighting',
    parentId: null,
    imageUrl: 'https://images.tavkil.com/categories/lighting.jpg',
    displayOrder: 2,
    status: 'published',
    createdAt: '2026-01-15T09:00:00.000Z',
    updatedAt: '2026-05-22T08:10:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Lighting',
        slug: 'lighting',
        description: 'LED panels, decorative fixtures, and commercial lighting.',
        seoTitle: 'Wholesale Commercial Lighting',
        seoDescription: 'LED panels and decorative fixtures for hospitality and retail fitouts.',
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Aydınlatma',
        slug: 'aydinlatma',
        description: 'LED paneller, dekoratif armatürler ve ticari aydınlatma.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'الإضاءة',
        slug: 'al-idaa',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-industrial',
    parentId: null,
    imageUrl: null,
    displayOrder: 3,
    status: 'draft',
    createdAt: '2026-02-01T09:00:00.000Z',
    updatedAt: '2026-05-25T14:45:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Industrial Equipment',
        slug: 'industrial-equipment',
        description: 'Pumps, seals, and industrial machinery parts.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Endüstriyel Ekipman',
        slug: 'endustriyel-ekipman',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: '',
        slug: '',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-bath-towels',
    parentId: 'cat-textiles',
    imageUrl: 'https://images.tavkil.com/categories/bath-towels.jpg',
    displayOrder: 1,
    status: 'published',
    createdAt: '2026-01-13T09:00:00.000Z',
    updatedAt: '2026-05-20T11:35:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Bath Towels',
        slug: 'bath-towels',
        description: 'Cotton bath towels in multiple sizes and weights.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Banyo Havluları',
        slug: 'banyo-havlulari',
        description: 'Farklı ebat ve gramajlarda pamuklu banyo havluları.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'مناشف الحمام',
        slug: 'manashif-alhammam',
        description: 'مناشف حمام قطنية بأحجام وأوزان متعددة.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: true,
      },
    ],
  },
  {
    id: 'cat-hand-towels',
    parentId: 'cat-textiles',
    imageUrl: null,
    displayOrder: 2,
    status: 'published',
    createdAt: '2026-01-13T09:05:00.000Z',
    updatedAt: '2026-05-21T10:00:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Hand Towels',
        slug: 'hand-towels',
        description: 'Waffle and terry hand towels for hospitality use.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'El Havluları',
        slug: 'el-havlulari',
        description: 'Otelcilik için vafel ve havlu kumaşı el havluları.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'مناشف اليد',
        slug: 'manashif-alyad',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-led-panels',
    parentId: 'cat-lighting',
    imageUrl: null,
    displayOrder: 1,
    status: 'published',
    createdAt: '2026-01-16T09:00:00.000Z',
    updatedAt: '2026-05-22T08:15:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'LED Panels',
        slug: 'led-panels',
        description: 'Recessed and surface-mount LED panels for commercial ceilings.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'LED Paneller',
        slug: 'led-paneller',
        description: 'Ticari tavanlar için sıva altı ve sıva üstü LED paneller.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'ألواح LED',
        slug: 'alwah-led',
        description: 'ألواح LED غائرة وسطحية للأسقف التجارية.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: true,
      },
    ],
  },
  {
    id: 'cat-decorative-fixtures',
    parentId: 'cat-lighting',
    imageUrl: 'https://images.tavkil.com/categories/decorative-fixtures.jpg',
    displayOrder: 2,
    status: 'published',
    createdAt: '2026-01-16T09:05:00.000Z',
    updatedAt: '2026-05-22T08:20:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Decorative Fixtures',
        slug: 'decorative-fixtures',
        description: 'Pendants, chandeliers, and wall sconces for hospitality interiors.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Dekoratif Armatürler',
        slug: 'dekoratif-armaturler',
        description: 'Otelcilik mekânları için avizeler ve aplikler.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'تجهيزات ديكورية',
        slug: 'tajhizat-dikuriya',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-commercial-lighting',
    parentId: 'cat-lighting',
    imageUrl: null,
    displayOrder: 3,
    status: 'draft',
    createdAt: '2026-02-03T09:00:00.000Z',
    updatedAt: '2026-05-24T16:00:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Commercial Lighting',
        slug: 'commercial-lighting',
        description: 'High-bay, track, and floodlighting for warehouses and retail.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Ticari Aydınlatma',
        slug: 'ticari-aydinlatma',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: '',
        slug: '',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-pumps',
    parentId: 'cat-industrial',
    imageUrl: 'https://images.tavkil.com/categories/pumps.jpg',
    displayOrder: 1,
    status: 'draft',
    createdAt: '2026-02-01T09:10:00.000Z',
    updatedAt: '2026-05-25T14:50:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Pumps',
        slug: 'pumps',
        description: 'Centrifugal and positive-displacement pumps for industrial use.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Pompalar',
        slug: 'pompalar',
        description: 'Endüstriyel kullanım için santrifüj pompalar.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: '',
        slug: '',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-seals-gaskets',
    parentId: 'cat-industrial',
    imageUrl: null,
    displayOrder: 2,
    status: 'draft',
    createdAt: '2026-02-01T09:15:00.000Z',
    updatedAt: '2026-05-25T14:55:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Seals & Gaskets',
        slug: 'seals-gaskets',
        description: 'Mechanical seals, O-rings, and industrial gaskets.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Salmastra & Conta',
        slug: 'salmastra-conta',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: '',
        slug: '',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: false,
        isMachineTranslated: false,
      },
    ],
  },
  {
    id: 'cat-bearings',
    parentId: 'cat-industrial',
    imageUrl: null,
    displayOrder: 3,
    status: 'draft',
    createdAt: '2026-02-01T09:20:00.000Z',
    updatedAt: '2026-05-25T15:00:00.000Z',
    translations: [
      {
        locale: 'en',
        name: 'Bearings',
        slug: 'bearings',
        description: 'Ball, roller, and thrust bearings for machinery.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: 'Rulmanlar',
        slug: 'rulmanlar',
        description: 'Makineler için bilyalı ve makaralı rulmanlar.',
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: 'محامل',
        slug: 'mahamil',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: true,
      },
    ],
  },
];

// ── Generated bulk categories (extra parents + sub-categories for scale) ──────
// Kept compact via a builder — English complete, TR present, AR intentionally
// left incomplete on some to exercise the locale badges + fallback.

function mkCategory(
  id: string,
  parentId: string | null,
  order: number,
  status: 'draft' | 'published',
  names: { en: string; tr: string; ar?: string },
): CategorySeed {
  const slug = (s: string) =>
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
  return {
    id,
    parentId,
    imageUrl: null,
    displayOrder: order,
    status,
    createdAt: '2026-03-01T09:00:00.000Z',
    updatedAt: '2026-05-28T09:00:00.000Z',
    translations: [
      {
        locale: 'en',
        name: names.en,
        slug: slug(names.en),
        description: `${names.en} — wholesale range.`,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'tr',
        name: names.tr,
        slug: slug(names.tr),
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: true,
        isMachineTranslated: false,
      },
      {
        locale: 'ar',
        name: names.ar ?? '',
        slug: names.ar ? slug(id) + '-ar' : '',
        description: null,
        seoTitle: null,
        seoDescription: null,
        isComplete: !!names.ar,
        isMachineTranslated: !!names.ar,
      },
    ],
  };
}

// parent → its sub-categories (name triples). Generates parents + subs at once.
const GENERATED_TREE: {
  parent: { id: string; en: string; tr: string; ar?: string; status: 'draft' | 'published' };
  subs: { id: string; en: string; tr: string; ar?: string; status: 'draft' | 'published' }[];
}[] = [
  {
    parent: {
      id: 'cat-kitchenware',
      en: 'Kitchenware',
      tr: 'Mutfak Eşyaları',
      ar: 'أدوات المطبخ',
      status: 'published',
    },
    subs: [
      {
        id: 'cat-cookware',
        en: 'Cookware',
        tr: 'Pişirme Kapları',
        ar: 'أواني الطهي',
        status: 'published',
      },
      {
        id: 'cat-utensils',
        en: 'Utensils',
        tr: 'Mutfak Gereçleri',
        ar: 'أدوات',
        status: 'published',
      },
      { id: 'cat-food-storage', en: 'Food Storage', tr: 'Saklama Kapları', status: 'published' },
      { id: 'cat-drinkware', en: 'Drinkware', tr: 'İçecek Bardakları', status: 'draft' },
    ],
  },
  {
    parent: {
      id: 'cat-packaging',
      en: 'Packaging',
      tr: 'Ambalaj',
      ar: 'التغليف',
      status: 'published',
    },
    subs: [
      { id: 'cat-boxes', en: 'Boxes & Cartons', tr: 'Kutular', ar: 'صناديق', status: 'published' },
      { id: 'cat-bags', en: 'Bags & Pouches', tr: 'Torbalar', status: 'published' },
      { id: 'cat-labels', en: 'Labels & Tape', tr: 'Etiketler', status: 'published' },
    ],
  },
  {
    parent: {
      id: 'cat-safety',
      en: 'Safety Equipment',
      tr: 'Güvenlik Ekipmanı',
      ar: 'معدات السلامة',
      status: 'published',
    },
    subs: [
      { id: 'cat-gloves', en: 'Gloves', tr: 'Eldivenler', ar: 'قفازات', status: 'published' },
      { id: 'cat-helmets', en: 'Helmets', tr: 'Kasklar', status: 'published' },
      { id: 'cat-hi-vis', en: 'Hi-Vis Vests', tr: 'Reflektörlü Yelekler', status: 'draft' },
    ],
  },
  {
    parent: { id: 'cat-flooring', en: 'Flooring', tr: 'Zemin Kaplama', status: 'published' },
    subs: [
      { id: 'cat-tiles', en: 'Ceramic Tiles', tr: 'Seramik Karolar', status: 'published' },
      { id: 'cat-vinyl', en: 'Vinyl Flooring', tr: 'Vinil Zemin', status: 'published' },
      { id: 'cat-carpet', en: 'Carpet Tiles', tr: 'Karo Halı', status: 'draft' },
    ],
  },
];

const GENERATED_CATEGORIES: CategorySeed[] = GENERATED_TREE.flatMap((group, gi) => [
  mkCategory(group.parent.id, null, 10 + gi, group.parent.status, group.parent),
  ...group.subs.map((s, si) => mkCategory(s.id, group.parent.id, si + 1, s.status, s)),
]);

export const CATEGORIES: AdminCategory[] = [...BASE_CATEGORIES, ...GENERATED_CATEGORIES].map(
  (c) => ({ sortStrategy: 'manual', ...c }),
);

/** Find a category by id (case-sensitive — ids are stable slugs). */
export function findCategory(id: string | undefined): AdminCategory | undefined {
  if (!id) return undefined;
  return CATEGORIES.find((c) => c.id === id);
}
